/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AzureDeploy {
  /**
   * The name of the project.
   */
  project: string;
  /**
   * The name of the application.
   */
  name?: string;
  /**
   * The directory of the new application.
   */
  directory?: string;
  /**
   * Add tags to the application (used for linting)
   */
  tags?: string;
  [k: string]: unknown;
}
