/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
import { JsonObject } from '@angular-devkit/core';
export interface AzureDeployBuilderSchema extends JsonObject {
  /**
   * Azure container name?
   */
  containerName?: string;
  /**
   * Directory of deployable code
   */
  deployDir?: string;
}
